version: '3.8'

services:
  db:
    image: postgres:16
    container_name: gobuss_db
    environment:
      POSTGRES_DB: gobuss
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d gobuss"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./gobuss-back
    container_name: gobuss_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gobuss
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./gobuss-front
    container_name: gobuss_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
