# Database Configuration (Production)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:SomeDefaultSecretKeyForProductionChangeMe1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Brevo API Key
brevo.api.key=${BREVO_API_KEY:dummy_key}

jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never


# Flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
