# Database Configuration (Production)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:supersecretkeythatisatleast32characterslong}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Brevo API Key
brevo.api.key=${BREVO_API_KEY:dummy_key}
